### ISSUE TITLE
Create an optional `Dumper()` function

### ISSUE THREAD

**Issue by scottchiefbaker** [perlancar/perl-Data-Dump-Color#3]
I'd like to conditionally load `Data::Dump::Color` if it's available, and fall back to `Data::Dumper` if not. In this case, I'd need a `Dumper()` function in `Data::Dump::Color` as well so my calls will use the same function name. 

Is something like this possible? Right now I have to have a custom `out()` function like this to achieve this behavior: http://www.fpaste.org/293164/81357641/

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Hm, the Data::Dump module family and Data::Dumper don't have the same API. I'd be reluctant to add `Dumper()` because `dd()` or `dump()` and `Dumper()` are not exactly alike anyway. 

Since you're doing fallback code anyway, you can do something like this:

    BEGIN {
        no strict 'refs';
        *Dumper = eval { require Data::Dump::Color; 1 } && \&Data::Dump::Color::dd ||
            eval { require Data::Dump; 1 } && \&Data::Dump::dd ||
            do { require Data::Dumper; sub { print Data::Dumper::Dumper(@_) } };
    }

you can put that code in your custom module so it's as short to use as you want it to be.
